<?php

namespace App\Repository;

/**
 * DealerRangeManifiestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealerRangeManifiestoRepository extends \Doctrine\ORM\EntityRepository
{


    //Funcion que devuelve boolean si puede o no utilizar el rango en el que puede ser utilizado
    public function getRangeManifiestoBoo($manifiestoFrom, $manifiestoTo, $dealer){
        $add = "";
        if ($dealer != 0 && $dealer != ''){
            $add = " AND dealer_id = {$dealer}";
        }

        $sql = "	SELECT dr.id, d.id dealer_id, d.name, manifiesto_from, manifiesto_to
                        FROM dealer_range_manifiesto dr
                        	INNER JOIN dealer d ON (d.id = dr.dealer_id)

                        WHERE 
                        ( 
                         ({$manifiestoFrom} >= manifiesto_from AND 
                        {$manifiestoFrom} <= manifiesto_to) 
                        OR
                        ({$manifiestoTo} >= manifiesto_from AND 
                        {$manifiestoTo} <= manifiesto_to)
                        ) $add 
                        LIMIT 1";
//        echo $sql;
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

//        var_dump($execute);
        $arrReturn = array();
        $arrReturn["result"] =  empty($execute) ? 0 : 1;
        if($arrReturn["result"]){
            $arrReturn["info"] = $execute[0];
        }

        //$return = empty($execute) ? 0 : 1;

//        echo "RETURN $return***";
        //0 - no existe el rango
        //1 - si existe el rango
        return $arrReturn;
    }


    public function findByRange($code){


        $sql = "SELECT	dm.dealer_id
				FROM	dealer_range_manifiesto dm
				    INNER JOIN dealer d ON (d.id = dm.dealer_id)
				WHERE	({$code} >= manifiesto_from AND {$code} <= manifiesto_to)
				AND d.enabled = 1";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

        return $execute;
    }

    public function getByEnabledDealer(){
        $query = $this->createQueryBuilder('e');
        //ENABLED
        $query->innerJoin('e.dealer', 'd');
        $query->andWhere('d.enabled = 1');

        $results = $query->getQuery()->getResult();
        return $results;
    }
}
