<?php

namespace App\Repository;

/**
 * DealerNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealerNotificationRepository extends \Doctrine\ORM\EntityRepository
{


    public function clearTable(){

        $sql = "	DELETE FROM dealer_notification WHERE 1=1";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->executeStatement();

        return 1;

    }


    public function getDealersCountGuides($dealersNotification){

        date_default_timezone_set('America/Guatemala');


        $arrDealers = array();

        foreach ($dealersNotification as $d){

            $myDealerID = $d->getDealer()->getId();
            $gmdate = date("Y-m-d");
            $sql = "	SELECT  COUNT(g.id) guides
                        FROM    guide g
                            INNER JOIN manifiesto m ON (g.manifiesto_id = m.id)
                        WHERE   g.enabled = 1
                        AND     m.dealer_id = {$myDealerID}
                        AND     DATE(m.created_at) = '{$gmdate}'";


            //print $sql;die;

            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $result = $stmt->executeQuery();
            $execute = $result->fetchAllAssociative();

            $guides =  intval($execute[0]["guides"]);

            if($guides < 1){
                $arrDealers[$myDealerID] = trim($d->getDealer()->getName());
            }
        }


        return $arrDealers;


    }

    public function getByEnabledDealer(){
        $query = $this->createQueryBuilder('e');
        //ENABLED
        $query->innerJoin('e.dealer', 'd');
        $query->andWhere('d.enabled = 1');

        $results = $query->getQuery()->getResult();
        return $results;
    }

}
