<?php

namespace App\Repository;

/**
 * ManifiestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManifiestoRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTotalManifiesto($manifiestoID){

        $sql = "SELECT 	SUM(g.price) + m.extra_amount manifiestoTotal
                FROM	guide g
                    INNER JOIN manifiesto m ON (g.manifiesto_id = m.id)
                    INNER JOIN service s ON (g.service_id = s.id)
                WHERE   m.id = {$manifiestoID}
                AND     s.claim_payment = 0";
        //AND m.enabled = 1

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

        return $execute[0]["manifiestoTotal"];
    }

    public function getTotalBalanceManifiesto($manifiestoID){

        $sql = "SELECT 	SUM(g.price) manifiestoTotal
                FROM	guide g
                    INNER JOIN manifiesto m ON (g.manifiesto_id = m.id)
                    INNER JOIN service s ON (g.service_id = s.id)
                WHERE   m.id = {$manifiestoID}
                AND     s.claim_payment = 0";
        //AND m.enabled = 1

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

        return $execute[0]["manifiestoTotal"];
    }


    public function getPaymentManifiesto($manifiestoID){

        //SUM credit, check_amount, voucher_amount, cash

        $sql = "    SELECT 	m.cash + credit + check_amount + voucher_amount + voucher2_amount + voucher3_amount  payment
                    FROM    manifiesto m
                    WHERE   m.id = {$manifiestoID}";
        //AND m.enabled = 1

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

        return $execute[0]["payment"];
    }


    public function getRequiredManifiestoData($filters = null)
    {

        date_default_timezone_set('America/Guatemala');
        // Create Main Query
        $query = $this->createQueryBuilder('e');
        //ENABLED
        $query->andWhere("e.enabled = 1");

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //JOINS
        $query->innerJoin('e.dealer', 'd');
        $countQuery->innerJoin('e.dealer', 'd');

        //var_dump($filters);die;

        ///FILTERS

        // Add date condition
        $filterDateFrom = $filters["filter_from"];
        $filterDateTo = $filters["filter_to"];

        $query->andWhere('e.createdAt >= :startDate AND e.createdAt <= :endDate')
            ->setParameter('startDate', date("Y-m-d H:i:s", strtotime($filterDateFrom)) )
            ->setParameter('endDate', date('Y-m-d H:i:s', strtotime($filterDateTo . ' +1 day')));

        $countQuery->andWhere('e.createdAt >= :startDate AND e.createdAt <= :endDate')
            ->setParameter('startDate', date("Y-m-d H:i:s", strtotime($filterDateFrom)) )
            ->setParameter('endDate', date('Y-m-d H:i:s', strtotime($filterDateTo . ' +1 day')));

        //dealer
        $filterDealer = $filters["filter_dealer"];
        if($filterDealer > 0){
            $query->andWhere('d.id = :myDealer')
                ->setParameter('myDealer', $filterDealer);
            $countQuery->andWhere('d.id = :myDealer')
                ->setParameter('myDealer', $filterDealer);
        }


        ///type
        if(intval($filters["type"]) != 0){
            if($filters["type"] == 1){
                $status = 'Pendiente de Pago';
            }
            else if($filters["type"] == 2){
                $status = 'Cancelado';
            }

            $query->andWhere('e.status = :status')
                ->setParameter('status', $status);
            $countQuery->andWhere('e.status = :status')
                ->setParameter('status', $status);
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        /*
        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
        */

        return $results;

    }


    public function getRequiredManifiestoDTData($start, $length, $orders, $search, $columns, $filters = null)
    {

        date_default_timezone_set('America/Guatemala');
        // Create Main Query
        $query = $this->createQueryBuilder('e');
        //ENABLED
        $query->andWhere("e.enabled = 1");

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //JOINS
        $query->innerJoin('e.dealer', 'd');
        $countQuery->innerJoin('e.dealer', 'd');

        //var_dump($filters);die;

        ///FILTERS
        // Add date condition
        $filterDateFrom = $filters["filter_from"];
        $filterDateTo = $filters["filter_to"];

        $query->andWhere('e.createdAt >= :startDate AND e.createdAt <= :endDate')
            ->setParameter('startDate', date("Y-m-d H:i:s", strtotime($filterDateFrom)) )
            ->setParameter('endDate', date('Y-m-d H:i:s', strtotime($filterDateTo . ' +1 day')));

        $countQuery->andWhere('e.createdAt >= :startDate AND e.createdAt <= :endDate')
            ->setParameter('startDate', date("Y-m-d H:i:s", strtotime($filterDateFrom)) )
            ->setParameter('endDate', date('Y-m-d H:i:s', strtotime($filterDateTo . ' +1 day')));

        //dealer
        $filterDealer = $filters["filter_dealer"];
        if($filterDealer > 0){
            $query->andWhere('d.id = :myDealer')
                ->setParameter('myDealer', $filterDealer);
            $countQuery->andWhere('d.id = :myDealer')
                ->setParameter('myDealer', $filterDealer);
        }


        //vouchear
        if(isset($filters["filter_voucher"]) && trim($filters["filter_voucher"]) != "" ){

            $query->andWhere("e.voucherNumber = :myVoucher OR e.voucher2Number = :myVoucher OR e.voucher3Number = :myVoucher")
                ->setParameter('myVoucher', trim($filters["filter_voucher"]));
            $countQuery->andWhere("e.voucherNumber = :myVoucher OR e.voucher2Number = :myVoucher OR e.voucher3Number = :myVoucher")
                ->setParameter('myVoucher', trim($filters["filter_voucher"]));

        }


        ///type
        if(intval($filters["type"]) != 0){

            if($filters["type"] == 1){
                $status = 'Pendiente de Pago';
            }
            else if($filters["type"] == 2){
                $status = 'Cancelado';
            }

            $query->andWhere('e.status = :status')
                ->setParameter('status', $status);
            $countQuery->andWhere('e.status = :status')
                ->setParameter('status', $status);

        }



        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {

                    case 'dealer':
                    {
                        $searchQuery = 'd.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'code':
                    {
                        $searchQuery = 'e.code LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'status':
                    {
                        $searchQuery = 'e.status LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'observation':
                    {
                        $searchQuery = 'e.observation LIKE \'%'.$searchItem.'%\'';
                        break;
                    }


                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'code':
                    {
                        $orderColumn = 'e.code';
                        break;
                    }
                    case 'createdAt':
                    {
                        $orderColumn = 'e.createdAt';
                        break;
                    }

                    case 'dealer':
                    {
                        $orderColumn = 'd.name';
                        break;
                    }
                    case 'total':
                    {
                        $orderColumn = 'e.total';
                        break;
                    }
                    case 'balance':
                    {
                        $orderColumn = 'e.balance';
                        break;
                    }
                    case 'taxTotal':
                    {
                        $orderColumn = 'e.taxTotal';
                        break;
                    }
                    case 'taxBalance':
                    {
                        $orderColumn = 'e.taxBalance';
                        break;
                    }

                    case 'status':
                    {
                        $orderColumn = 'e.status';
                        break;
                    }
                    case 'observation':
                    {
                        $orderColumn = 'e.observation';
                        break;
                    }
                    case 'credit':
                    {
                        $orderColumn = 'e.credit';
                        break;
                    }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }

    public function findByDealerByStatus($status = NULL){


        $strFilter = "";
        if($status != NULL){
           $strFilter = " WHERE m.status = '{$status}' ";
        }

        $sql = "SELECT DISTINCT(d.id), d.name, d.credit
                FROM dealer d
                INNER JOIN manifiesto m ON m.dealer_id = d.id
                {$strFilter}
                AND m.enabled = 1
                AND d.enabled = 1
                ORDER BY d.name";
//        echo $sql;s
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

        return $execute;
    }

    //getGeoData

    public function getGeoData($from, $to, $dealer, $service){


        $filterService = "";
        if($service != 0 && $service != ''){
            $filterService = " AND     g.service_id = {$service} ";
        }

        $filterDealer = "";
        if($dealer != 0 && $dealer != ''){
            $filterDealer = " AND     m.dealer_id = {$dealer} ";
        }

        $sql = "    
                    SELECT	COUNT(g.id) stateCount, s.id, s.name, s.chart_name
                    FROM 	guide g
                        INNER JOIN manifiesto m ON (m.id = g.manifiesto_id)
                        INNER JOIN dealer d ON (d.id = m.dealer_id)
                        INNER JOIN global_state s ON (s.id = d.state_id)
                    WHERE     (DATE(m.created_at) >= '{$from}' AND DATE(m.created_at) <= '{$to}')
                    AND m.enabled = 1
                    AND g.enabled = 1
                    {$filterDealer}
                    {$filterService}
                    GROUP BY s.id
                    ORDER BY stateCount DESC";


        //print $sql;die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

        if(!empty($execute)){
            //print "<pre>";
            //var_dump($execute);die;
            return $execute;
        }
        else{
            return array();
        }


    }




    public function getGeoMoneyData($from, $to, $dealer, $service){



        $filterService = "";
        if($service != 0 && $service != ''){
            $filterService = " AND     g.service_id = {$service} ";
        }

        $filterDealer = "";
        if($dealer != 0 && $dealer != ''){
            $filterDealer = " AND     m.dealer_id = {$dealer} ";
        }

        $sql = "    
                    SELECT	SUM(g.price) stateTotal, s.id, s.name, s.chart_name
                    FROM 	guide g
                        INNER JOIN manifiesto m ON (m.id = g.manifiesto_id)
                        INNER JOIN dealer d ON (d.id = m.dealer_id)
                        INNER JOIN global_state s ON (s.id = d.state_id)
                    WHERE     (DATE(m.created_at) >= '{$from}' AND DATE(m.created_at) <= '{$to}')
                    AND m.enabled = 1
                    AND g.enabled = 1
                    {$filterService}
                    {$filterDealer}
                    GROUP BY s.id
                    ORDER BY stateTotal DESC";

        //print $sql;die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

        if(!empty($execute)){
            //print "<pre>";
            //var_dump($execute);die;
            return $execute;
        }
        else{
            return array();
        }


    }






}
