<?php

namespace App\Repository;

use App\Entity\Rate;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Rate::class);
    }


    public function getRatesByCategory($categoryID){


        $sql = "	    SELECT 	r.id, r.weight, r.price, r.commission,
	                            s.id serviceID, s.name serviceName
	                            
						FROM	rate r
						    INNER JOIN service s ON(s.id = r.service_id)
						    INNER JOIN category c ON(c.id = r.category_id)
						WHERE	c.id = '{$categoryID}'
						AND		s.enabled = 1
						AND     r.enabled = 1
						ORDER BY s.id, r.weight";



        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();


        return $execute;
    }


    public function getRequiredDTData($start, $length, $orders, $search, $columns, $otherConditions = null)
    {
        // Create Main Query
        $query = $this->createQueryBuilder('e');

        //ENABLED
        $query->andWhere("e.enabled = 1");

        // Create Count Query
        $countQuery = $this->createQueryBuilder('e');
        $countQuery->select('COUNT(e)');

        //JOINS
        $query->join('e.service', 's');
        $countQuery->join('e.service', 's');

        $query->join('e.category', 'c');
        $countQuery->join('e.category', 'c');

        //filter by enabled service
        $query->andWhere("s.enabled = 1");
        $countQuery->andWhere("s.enabled = 1");



        // Fields Search
        foreach ($columns as $key => $column)
        {
            if ($column['search']['value'] != '')
            {
                // $searchItem is what we are looking for
                $searchItem = $column['search']['value'];
                $searchQuery = null;

                switch($column['name'])
                {
                    case 'id':
                    {
                        $searchQuery = 'e.id ='. $searchItem;
                        break;
                    }
                    case 'service':
                    {
                        $searchQuery = 's.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'category':
                    {
                        $searchQuery = 'c.name LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'weight':
                    {
                        $searchQuery = 'e.weight LIKE \'%'.$searchItem.'%\'';
                        break;
                    }

                    case 'price':
                    {
                        $searchQuery = 'e.price LIKE \'%'.$searchItem.'%\'';
                        break;
                    }
                    case 'commission':
                    {
                        $searchQuery = 'e.commission LIKE \'%'.$searchItem.'%\'';
                        break;
                    }


                }


                if ($searchQuery !== null)
                {
                    $query->andWhere($searchQuery);
                    $countQuery->andWhere($searchQuery);
                }
            }
        }

        // Limit
        $query->setFirstResult($start)->setMaxResults($length);

        // Order
        // Orders
        foreach ($orders as $key => $order)
        {
            // Orders does not contain the name of the column, but its number,
            // so add the name so we can handle it just like the $columns array
            $orders[$key]['name'] = $columns[$order['column']]['name'];
        }

        foreach ($orders as $key => $order)
        {

            // $order['name'] is the name of the order column as sent by the JS
            if ($order['name'] != '')
            {
                $orderColumn = null;

                switch($order['name'])
                {
                    case 'id':
                    {
                        $orderColumn = 'e.id';
                        break;
                    }
                    case 'service':
                    {
                        $orderColumn = 's.name';
                        break;
                    }

                    case 'category':
                    {
                        $orderColumn = 'c.name';
                        break;
                    }
                    case 'weight':
                    {
                        $orderColumn = 'e.weight';
                        break;
                    }
                    case 'price':
                    {
                        $orderColumn = 'e.price';
                        break;
                    }

                    case 'commission':
                    {
                        $orderColumn = 'e.commission';
                        break;
                    }

                }

                if ($orderColumn !== null)
                {
                    $query->orderBy($orderColumn, $order['dir']);
                }
            }
        }


        $results = $query->getQuery()->getResult();
        $countResult = $countQuery->getQuery()->getSingleScalarResult();

        return array(
            "results" 		=> $results,
            "countResult"	=> $countResult
        );
    }

    public function getMyRate($serviceID, $categoryID, $weight){


        $sql = "	    SELECT 	id
	                            
						FROM	rate
						WHERE	category_id = {$categoryID}
						AND		service_id = {$serviceID}
						AND     weight = '{$weight}'
						AND     enabled = 1
						LIMIT 1
						";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();
        if(!empty($execute)){
            return intval($execute[0]["id"]);
        }
        else{
            return NULL;
        }


    }

}
