<?php

namespace App\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTopByOrders($from, $to, $dealer, $service){


        $filterService = "";
        if($service != 0 && $service != ''){
            $filterService = " AND     g.service_id = {$service} ";
        }

        $filterDealer = "";
        if($dealer != 0 && $dealer != ''){
            $filterDealer = " AND     m.dealer_id = {$dealer} ";
        }


        $sql = "    SELECT  COUNT(g.id) guides, s.id service_id, s.name service_name
                    FROM    guide g
                        INNER JOIN service s ON (g.service_id = s.id)
                        INNER JOIN manifiesto m ON (g.manifiesto_id = m.id)
                    WHERE   g.enabled = 1  
                    AND     (DATE(m.created_at) >= '{$from}' AND DATE(m.created_at) <= '{$to}')
                    {$filterService}
                    {$filterDealer}
                    GROUP BY s.id
                    ORDER BY guides DESC";
                    //LIMIT 30";


        //print $sql;die;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $result = $stmt->executeQuery();
        $execute = $result->fetchAllAssociative();

        if(!empty($execute)){
            return $execute;
        }
        else{
            return array();
        }


    }


}
