<?php

namespace App\Repository;

/**
 * DealerNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDealerRepository extends \Doctrine\ORM\EntityRepository
{


    public function clearTable($user){

        $sql = "DELETE FROM user_dealer WHERE user = {$user}";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->executeStatement();

        return 1;

    }



}
